repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: (^automator_api/migrations/)|
          (?x)^(
              manage.py
          )$
        args:
          [
            "-rn",
            "--django-settings-module=automator_project.settings",
            "--load-plugins=pylint_django,pylint.extensions.no_self_use",
            "--rcfile=./.pylintrc",
          ]
