# Generated by Django 4.1.1 on 2022-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automator_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='techs',
            field=models.ManyToManyField(to='automator_api.tech'),
        ),
    ]
