# Generated by Django 4.1.3 on 2022-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automator_api', '0002_cohort_techs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
