# Generated by Django 4.1 on 2022-08-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automator_api', '0002_remove_project_image_project_deployed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_quote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='podcast_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
