# Generated by Django 4.1.3 on 2022-12-06 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automator_api', '0004_cohort_repo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='github_organization',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='automator_api.cohort'),
        ),
    ]
