# Generated by Django 4.1.3 on 2022-12-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automator_api', '0005_alter_cohort_github_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='automator_api.cohort'),
        ),
    ]
